# Generated by Django 4.1.2 on 2022-12-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[('candidate', 'Candidate'), ('recruiter', 'Recruiter')], max_length=20)),
                ('identifier', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('profile_bio', models.TextField(blank=True, max_length=500)),
                ('zip_code', models.CharField(max_length=10)),
                ('skills', models.TextField()),
                ('github_username', models.CharField(blank=True, max_length=100)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('education', models.CharField(blank=True, max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_website', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
