# Generated by Django 4.1.2 on 2022-12-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company_website',
        ),
        migrations.RemoveField(
            model_name='user',
            name='github_username',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_bio',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.TextField(max_length=50),
        ),
    ]
